// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd52WMRHiS8nlSnmz9FIefwmJ9Run9F4I',
    appId: '1:811724095533:web:66b043ac41f37714e2f8a4',
    messagingSenderId: '811724095533',
    projectId: 'airbnnb-ac49f',
    authDomain: 'airbnnb-ac49f.firebaseapp.com',
    storageBucket: 'airbnnb-ac49f.firebasestorage.app',
    measurementId: 'G-PCDNH5K1FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzrywNWe-QIFkM7H_n4GDeGKc0A0FzHUs',
    appId: '1:811724095533:android:3fcd39011ba06e18e2f8a4',
    messagingSenderId: '811724095533',
    projectId: 'airbnnb-ac49f',
    storageBucket: 'airbnnb-ac49f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWc6ZgUdIeWKlHGlOt5XxoTIPWcsqj2FE',
    appId: '1:811724095533:ios:bb21568a0ac180e9e2f8a4',
    messagingSenderId: '811724095533',
    projectId: 'airbnnb-ac49f',
    storageBucket: 'airbnnb-ac49f.firebasestorage.app',
    iosBundleId: 'com.example.airbnbAppUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWc6ZgUdIeWKlHGlOt5XxoTIPWcsqj2FE',
    appId: '1:811724095533:ios:bb21568a0ac180e9e2f8a4',
    messagingSenderId: '811724095533',
    projectId: 'airbnnb-ac49f',
    storageBucket: 'airbnnb-ac49f.firebasestorage.app',
    iosBundleId: 'com.example.airbnbAppUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd52WMRHiS8nlSnmz9FIefwmJ9Run9F4I',
    appId: '1:811724095533:web:0edaccce1254b27fe2f8a4',
    messagingSenderId: '811724095533',
    projectId: 'airbnnb-ac49f',
    authDomain: 'airbnnb-ac49f.firebaseapp.com',
    storageBucket: 'airbnnb-ac49f.firebasestorage.app',
    measurementId: 'G-SC0P0XG5DV',
  );
}
